### ISSUE TITLE
Configuration file syntax

### ISSUE THREAD

**Issue by bennigraf** [DirkR/capturadio#17]
Hi!

There seems to be some trouble in how the default configuration file is rendered after setup, especially with the shows-line in a station definition. When it's written as 
```
shows = [Show(id=bobharriscountry, name=Bob Harris Country, duration=3480, station_id=bbc2)]
```
I get the error 
```
Exception: No "title" or "name" option defined for show "[Show(id=bobharriscountry".
```
When I remove that line and have the show configured in it's own section, recording works.

(Also capturadiorc.example seems a bit outdatet ;-)...)

**Comment by DirkR** [comment]
Hi @bennigraf ,

thanks for your feedback!
I was away for some days, but now I could reproduce this error and will fix it ASAP.

Best regards
Dirk

**Comment by DirkR** [comment]
Finally I repaired the script and updated the sample configuration.
I should give a little bit more love to this project, as I have some interesting features in mind. But it just works actually... ;)

Thanks for your feedback!

**Comment by mro** [comment]
Hi @DirkR are you interested in joining forces with (my) https://github.com/mro/radio-pi ?

I think of dumping lua and ruby and porting it to Go (which can run without installing dependencies).
